//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartWizard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PartWizard.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} breakable.
        /// </summary>
        internal static string Breakable {
            get {
                return ResourceManager.GetString("Breakable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        internal static string BreakSymmetryButtonText {
            get {
                return ResourceManager.GetString("BreakSymmetryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to break symmetry..
        /// </summary>
        internal static string BreakSymmetryDescription {
            get {
                return ResourceManager.GetString("BreakSymmetryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string DeletePartButtonText {
            get {
                return ResourceManager.GetString("DeletePartButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete the highlighted part..
        /// </summary>
        internal static string DeletePartDescription {
            get {
                return ResourceManager.GetString("DeletePartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred in {0}. If the error keeps occurring, please post a support request message in the AddOns forum thread for {0}. It will be very helpful to include as much information as possible, such as: steps to reproduce the problem, a .craft file, list of addons, and especially the log file at the following location on your computer:.
        /// </summary>
        internal static string GuiRenderErrorTextFormat {
            get {
                return ResourceManager.GetString("GuiRenderErrorTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not breakable, child {1} is not breakable.
        /// </summary>
        internal static string NotBreakableChildNotBreakable {
            get {
                return ResourceManager.GetString("NotBreakableChildNotBreakable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not breakable, counterpart {1} has no parent.
        /// </summary>
        internal static string NotBreakableCounterpartHasNoParent {
            get {
                return ResourceManager.GetString("NotBreakableCounterpartHasNoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not breakable, has an ancestral counterpart.
        /// </summary>
        internal static string NotBreakableHasAncestralCounterpart {
            get {
                return ResourceManager.GetString("NotBreakableHasAncestralCounterpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not breakable, has descendant counterpart.
        /// </summary>
        internal static string NotBreakableHasDescendantCounterpart {
            get {
                return ResourceManager.GetString("NotBreakableHasDescendantCounterpart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not breakable, has no parent.
        /// </summary>
        internal static string NotBreakableNoParent {
            get {
                return ResourceManager.GetString("NotBreakableNoParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not breakable, not symmetrical.
        /// </summary>
        internal static string NotBreakableNotSymmetrical {
            get {
                return ResourceManager.GetString("NotBreakableNotSymmetrical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Part(s).
        /// </summary>
        internal static string StatusLabelTextFormat {
            get {
                return ResourceManager.GetString("StatusLabelTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Part(s), {1}.
        /// </summary>
        internal static string StatusLabelTooltipTextFormat {
            get {
                return ResourceManager.GetString("StatusLabelTooltipTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry Editor - {0} ({1}).
        /// </summary>
        internal static string SymmetryEditor {
            get {
                return ResourceManager.GetString("SymmetryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ViewTypeAll {
            get {
                return ResourceManager.GetString("ViewTypeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string ViewTypeHidden {
            get {
                return ResourceManager.GetString("ViewTypeHidden", resourceCulture);
            }
        }
    }
}
